from .fixtures2d import FIXTURES2D, H1_HEXAGON_FIXTURE, M1_PENTAGON_FIXTURE, Q1_QUADRILATERAL_FIXTURE
from .internal_boundary_fixture import RegionWithInternalBoundaryFixture, SquareHoleRegionFixture
from .region2d import PentagonM1Region, QuadrilateralQ1Region, Region2D
